spring.application.name=api-gateway
server.port=9090
spring.main.web-application-type=reactive

# =========================
# ROUTES
# =========================

# USER + AUTH SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://3.110.167.15:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/users/**

# QUESTION SERVICE
spring.cloud.gateway.routes[1].id=question-service
spring.cloud.gateway.routes[1].uri=http://3.110.167.15:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/questions/**

# ANSWER SERVICE
spring.cloud.gateway.routes[2].id=answer-service
spring.cloud.gateway.routes[2].uri=http://3.110.167.15:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/answers/**

# NOTES SERVICE
spring.cloud.gateway.routes[3].id=notes-service
spring.cloud.gateway.routes[3].uri=http://3.110.167.15:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/notes/**


# =========================
# 🔥 GLOBAL CORS CONFIG (FIX)
# =========================

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://3.110.167.15:5173
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# 🔥 VERY IMPORTANT (handles OPTIONS at gateway)
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true